# Immagine base python
FROM python:3.9

RUN mkdir -p root/.aws

COPY aws/credentials   root/.aws/
COPY aws/config        root/.aws/

# directory di lavoro all'interno del container
WORKDIR /app

# Copy dei file necessari
COPY hanoi.py .
COPY GUI/config.json   .

# Install dipendenze
RUN pip install flask
RUN pip install boto3

# Avvio
CMD ["python", "hanoi.py"]