# Immagine base python
FROM python:3.9

RUN mkdir -p root/.aws

COPY utility_container/aws/credentials   root/.aws/
COPY utility_container/aws/config        root/.aws/

# directory di lavoro all'interno del container
WORKDIR /app

# Copy dei file necessari
COPY utility_container/funzioni/merge_sort.py .
COPY GUI/config.json   .

# Install dipendenze
RUN pip install flask
RUN pip install boto3

# Avvio
CMD ["python", "merge_sort.py"]